# kind: Secret
# apiVersion: v1
# metadata:
#   name: ecommerce-secret
#   namespace: devops-app
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
#   MYSQL_PASSWORD: YWRtaW4xMjM=
#   DB_PASSWORD: eW91cl9wYXNzd29yZA==  

apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: devops-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_PASSWORD: admin123
  DB_PASSWORD: admin123